apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { worker_connections 2048; }
    http {
      limit_req_zone $binary_remote_addr zone=req_limit:10m rate=1000r/s;
      
      # Gzip para gastar CPU (ajuda no scaling)
      gzip on;
      gzip_min_length 0;
      gzip_types text/html;

      server {
        listen 80;
        keepalive_timeout 0; 
        
        # Define a diretoria base para servir ficheiros
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
          # Burst 0 + Nodelay = Tolerância Zero
          limit_req zone=req_limit nodelay;
          

        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  selector:
    matchLabels:
      app: demo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            cpu: "5m"
          limits:
            cpu: "200m"
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
spec:
  selector:
    app: demo-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-api
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 10